"""add h1b sponsorship fields to companies and oews_wages table

Revision ID: 16e1cf02645f
Revises: c7040c0a371e
Create Date: 2026-09-10 20:13:07.407846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e1cf02645f'
down_revision: Union[str, Sequence[str], None] = 'c7040c0a371e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oews_wages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soc_code', sa.String(), nullable=False),
    sa.Column('soc_title', sa.String(), nullable=True),
    sa.Column('area_title', sa.String(), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('wage_level_1', sa.Float(), nullable=True),
    sa.Column('wage_level_2', sa.Float(), nullable=True),
    sa.Column('wage_level_3', sa.Float(), nullable=True),
    sa.Column('wage_level_4', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soc_code', 'area_title', 'source_year', name='uq_oews_wage_soc_area_year')
    )
    op.create_index(op.f('ix_oews_wages_area_title'), 'oews_wages', ['area_title'], unique=False)
    op.create_index(op.f('ix_oews_wages_id'), 'oews_wages', ['id'], unique=False)
    op.create_index(op.f('ix_oews_wages_soc_code'), 'oews_wages', ['soc_code'], unique=False)
    op.add_column('companies', sa.Column('h1b_approvals_total', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('h1b_denials_total', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('h1b_last_fiscal_year', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('sponsorship_tier', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('h1b_data_updated_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('lca_filings_total', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('lca_last_fiscal_quarter', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('lca_data_updated_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('is_cap_exempt', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('cap_exempt_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###
    # (autogenerate also proposed nullable=True alter_columns on 6 unrelated
    # global_settings columns -- pre-existing model/DB drift from an earlier
    # migration, not part of this change. Left untouched here; not this
    # migration's concern.)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'cap_exempt_reason')
    op.drop_column('companies', 'is_cap_exempt')
    op.drop_column('companies', 'lca_data_updated_at')
    op.drop_column('companies', 'lca_last_fiscal_quarter')
    op.drop_column('companies', 'lca_filings_total')
    op.drop_column('companies', 'h1b_data_updated_at')
    op.drop_column('companies', 'sponsorship_tier')
    op.drop_column('companies', 'h1b_last_fiscal_year')
    op.drop_column('companies', 'h1b_denials_total')
    op.drop_column('companies', 'h1b_approvals_total')
    op.drop_index(op.f('ix_oews_wages_soc_code'), table_name='oews_wages')
    op.drop_index(op.f('ix_oews_wages_id'), table_name='oews_wages')
    op.drop_index(op.f('ix_oews_wages_area_title'), table_name='oews_wages')
    op.drop_table('oews_wages')
    # ### end Alembic commands ###
