"""add tavily/hunter monthly call-budget tracking to global_settings

Revision ID: 366cc063786a
Revises: b220e9f83c45
Create Date: 2026-08-23 19:35:59.198887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366cc063786a'
down_revision: Union[str, Sequence[str], None] = 'b220e9f83c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adjusted from the raw autogenerate output: server_default backfills
    # the already-existing global_settings row with the real Python-side
    # defaults instead of leaving them NULL -- contact_discovery_service.
    # py's _consume_budget() does `used >= budget`, which raises TypeError
    # against a NULL/None value on the live row (same class of gotcha as
    # min_score_for_auto_launch's migration).
    op.add_column('global_settings', sa.Column('tavily_monthly_call_budget', sa.Integer(), nullable=False, server_default='1000'))
    op.add_column('global_settings', sa.Column('tavily_calls_used_this_month', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('global_settings', sa.Column('tavily_month_reset_at', sa.DateTime(), nullable=True))
    op.add_column('global_settings', sa.Column('hunter_monthly_call_budget', sa.Integer(), nullable=False, server_default='25'))
    op.add_column('global_settings', sa.Column('hunter_calls_used_this_month', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('global_settings', sa.Column('hunter_month_reset_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'hunter_month_reset_at')
    op.drop_column('global_settings', 'hunter_calls_used_this_month')
    op.drop_column('global_settings', 'hunter_monthly_call_budget')
    op.drop_column('global_settings', 'tavily_month_reset_at')
    op.drop_column('global_settings', 'tavily_calls_used_this_month')
    op.drop_column('global_settings', 'tavily_monthly_call_budget')
    # ### end Alembic commands ###
