"""add workable and smartrecruiters board slug columns

Revision ID: 48244f109545
Revises: 16e1cf02645f
Create Date: 2026-09-10 21:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48244f109545'
down_revision: Union[str, Sequence[str], None] = '16e1cf02645f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written, not autogenerated -- the live DB is currently behind
    # head (16e1cf02645f isn't deployed yet either), so autogenerate has
    # no accurate base to diff against right now. Same simple nullable-
    # String pattern as every other *_slug column on Company (see
    # greenhouse_slug etc. in app/models.py), so hand-writing this one is
    # low-risk.
    op.add_column('companies', sa.Column('workable_slug', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('smartrecruiters_slug', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('companies', 'smartrecruiters_slug')
    op.drop_column('companies', 'workable_slug')
