"""add interview process research and behavioral story bank

Revision ID: 5c5f381763b8
Revises: 5b48b4e511e0
Create Date: 2026-08-26 02:15:49.603573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5f381763b8'
down_revision: Union[str, Sequence[str], None] = '5b48b4e511e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('situation', sa.Text(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('traits_json', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['profile_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_stories_id'), 'behavioral_stories', ['id'], unique=False)
    op.add_column('interview_prep', sa.Column('process_research_json', sa.Text(), nullable=True))
    op.add_column('interview_prep', sa.Column('predicted_rounds_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_prep', 'predicted_rounds_json')
    op.drop_column('interview_prep', 'process_research_json')
    op.drop_index(op.f('ix_behavioral_stories_id'), table_name='behavioral_stories')
    op.drop_table('behavioral_stories')
    # ### end Alembic commands ###
