"""add admin_accounts table for real login/signup/password-reset

Revision ID: b220e9f83c45
Revises: fae07861e8f5
Create Date: 2026-08-23 18:44:39.845235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b220e9f83c45'
down_revision: Union[str, Sequence[str], None] = 'fae07861e8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_settings', 'min_score_for_auto_launch',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('65'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_settings', 'min_score_for_auto_launch',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('65'))
    # ### end Alembic commands ###
