"""add per-posting wage level fields and target soc code

Revision ID: b8ec1b14d258
Revises: dedf7ee1248e
Create Date: 2026-09-11 12:02:51.568554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ec1b14d258'
down_revision: Union[str, Sequence[str], None] = 'dedf7ee1248e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default matches the Python-side default (models.py) so the
    # one already-existing production GlobalSettings row gets a real
    # value instead of NULL -- get_or_create_settings only applies
    # Python-side defaults to a brand-new row, same convention as every
    # other GlobalSettings column added since fae07861e8f5.
    op.add_column('global_settings', sa.Column('target_soc_code', sa.String(), nullable=True, server_default='15-1252'))
    op.add_column('job_postings', sa.Column('offered_salary_min', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('offered_salary_max', sa.Integer(), nullable=True))
    op.add_column('job_postings', sa.Column('offered_salary_source', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('wage_level_per_posting', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'wage_level_per_posting')
    op.drop_column('job_postings', 'offered_salary_source')
    op.drop_column('job_postings', 'offered_salary_max')
    op.drop_column('job_postings', 'offered_salary_min')
    op.drop_column('global_settings', 'target_soc_code')
    # ### end Alembic commands ###
