"""add adaptive layer audit log and parameter value tables

Revision ID: dedf7ee1248e
Revises: cb15e27f46f6
Create Date: 2026-09-11 01:16:41.703106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedf7ee1248e'
down_revision: Union[str, Sequence[str], None] = 'cb15e27f46f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('subsystem', sa.String(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('triggering_evidence', sa.JSON(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reverted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('applied', 'proposed', 'approved', 'rejected', 'reverted')", name='ck_adaptation_log_status'),
    sa.CheckConstraint("tier IN ('tier1', 'tier2')", name='ck_adaptation_log_tier'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptation_log_id'), 'adaptation_log', ['id'], unique=False)
    op.create_index(op.f('ix_adaptation_log_subsystem'), 'adaptation_log', ['subsystem'], unique=False)
    op.create_table('adaptive_parameter_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter')
    )
    op.create_index(op.f('ix_adaptive_parameter_values_id'), 'adaptive_parameter_values', ['id'], unique=False)
    # ### end Alembic commands ###
    # (autogenerate also proposed nullable=True alter_columns on 7
    # unrelated global_settings columns from earlier migrations --
    # cosmetic Alembic drift, not this migration's concern.)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adaptive_parameter_values_id'), table_name='adaptive_parameter_values')
    op.drop_table('adaptive_parameter_values')
    op.drop_index(op.f('ix_adaptation_log_subsystem'), table_name='adaptation_log')
    op.drop_index(op.f('ix_adaptation_log_id'), table_name='adaptation_log')
    op.drop_table('adaptation_log')
    # ### end Alembic commands ###
