"""add min_score_for_auto_launch to global_settings

Revision ID: fae07861e8f5
Revises: 88907bf5c881
Create Date: 2026-08-23 04:29:26.990698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae07861e8f5'
down_revision: Union[str, Sequence[str], None] = '88907bf5c881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adjusted from the raw autogenerate output: server_default backfills
    # the already-existing global_settings row with the real Python-side
    # default (65) instead of leaving it NULL -- confirmation_service.py
    # compares this column directly against an int match_score, which
    # would raise TypeError against a NULL/None value on the live row.
    op.add_column(
        'global_settings',
        sa.Column('min_score_for_auto_launch', sa.Integer(), nullable=False, server_default='65'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'min_score_for_auto_launch')
    # ### end Alembic commands ###
